name: Release CD

on:
  release:
    paths:
      - '**.{tf|js}'
    types: [published]

jobs:
  infra:
    name: Provisioning infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.PROD_GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.PROD_GCP_SA_KEY }}
          project_id: ${{ secrets.PROD_PROJECT_ID }}
      - name: Activating GCloud account
        run:
          gcloud auth activate-service-account ${{ secrets.PROD_GCP_SA_EMAIL }}
          --key-file=client-secret.json

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.21
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: terraform
          tf_actions_comment: true
          args: '-backend-config=envs/prod/backend.tf'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: '../client-secret.json'
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.21
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: terraform
          tf_actions_comment: true
          args: '-var-file=envs/prod/prod.tfvars -out=plan.tfout'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: '../client-secret.json'
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}

      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.21
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: terraform
          tf_actions_comment: true
          args: '"plan.tfout"'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: '../client-secret.json'
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: infra
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm ci
      - run: npm test
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.PROD_GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.PROD_GCP_SA_KEY }}
          project_id: ${{ secrets.PROD_PROJECT_ID }}
      - name: Creating client-secrets.json
        run:
          gcloud auth activate-service-account ${{ secrets.PROD_GCP_SA_EMAIL }}
          --key-file=client-secret.json
      - name: Publish app to Google App Engine
        run: |
          # This client-secret.json is converted by PROD_GCP_SA_KEY.        
          gcloud config set project ${{ secrets.PROD_PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote
